use nerdstuff;

insert into producto(nombreProducto, costo, puntaje, descripcion, idCategoria, direccionFoto)
	values 	('Llavero Thor', 100, 7, 'Llavero de Mjolnir de Thor.', 2, '01.jpg'),
			('Playera Capitán América', 100, 7, 'Playera algodón Capitán América.', 1, '02.jpg'),
            ('Casco Iron Man', 2000, 120, 'Casco de plástico de Iron Man con luz interior.', 2, '03.jpg'),
            ('Cartera Deadpool', 300, 17, 'Cartera de piel con logo de Deadpool', 2, '04.jpg'),
            ('Figma Link', 1300, 80, 'Figura de plástico de Link.', 5, '05.jpg'),
            ('Taza Game of Thrones', 400, 22, 'Taza de cerámica de Game of Thrones.', 2, '06.jpg'),
            ('Funko Pop Goku', 350, 22, 'Figura de vinil de Goku.', 5, '07.jpg'),
            ('Funko Pop Mario', 350, 22, 'Figura de vinil de Mario.', 5, '08.jpg'),
            ('Funko Pop Daredevil', 350, 22, 'Figura de vinil de Daredevil.', 5, '09.jpg'),
            ('Gorra Nintendo', 500, 30, 'Gorra de tela con logo de Nintendo.', 1, '10.jpg'),
            ('Chamarra Overwatch', 1000, 70, 'Chamarra de piel con logo de Overwatch.', 1, '11.jpg'),
            ('Vaso Dragonball', 280, 16, 'Vaso de plástico de Dragon Ball', 2, '12.jpg'),
            ('Protector Celular Mario Bros', 175, 10, 'Protector de goma para celular de Mario Bros.', 2, '13.jpg'),
            ('Réplica Master Sword', 1900, 110, 'Réplica de metal a tamaño real de la Master Sword.', 4, '14.jpg'),
            ('Hebilla Fallout', 200, 14, 'Hebilla de metal de Fallout.', 2, '15.jpg'),
            ('Anillo Green Lantern', 300, 20, 'Anillo de metal de Linterna Verde.', 2, '16.jpg'),
            ('Esferas del Dragón', 600, 40, 'Esferas de plástico de Dragon Ball.', 4, '17.jpg'),
            ('Aretes Potara Dragon Ball', 200, 14, 'Aretes de metal con esferas de plástico de Dragon Ball.', 2, '18.jpg'),
            ('Manga Zelda 1', 180, 10, 'Manga de Legend of Zelda número 1 de 60 páginas.', 7, '19.jpg'),
            ('Manga Zelda 2', 180, 10, 'Manga de Legend of Zelda número 1 de 60 páginas.', 7, '20.jpg'),
            ('Manga Zelda 3', 180, 10, 'Manga de Legend of Zelda número 1 de 60 páginas.', 7, '21.jpg'),
            ('Hyrule Historia', 650, 40, 'Libro con la historia de Hyrule de Legend of Zelda.', 6, '22.jpg'),
            ('Peluche Pikachu', 200, 14, 'Figura de peluche de Pikachu.', 5, '23.jpg'),
            ('Llavero Zelda Boss Key', 175, 10, 'Llavero de metal de Boss Key de Legend of Zelda.', 2, '24.jpg'),
            ('Llavero Star Wars Vader', 175, 10, 'Llavero de metal de casco de Darth Vader de Star Wars.', 2, '25.jpg'),
            ('Cubo Rubik', 130, 10, 'Cubo Rubik de plástico.', 5, '26.jpg'),
            ('Llavero Chip', 40, 3, 'Llavero de circuito impreso.', 2, '27.jpg'),
            ('Mesa Control Nintendo', 1600, 100, 'Mesa con forma de Control de Nintendo.', 3, '28.jpg'),
            ('Banda Naruto', 120, 8, 'Banda de algodón con placa de metal de Naruto.', 2, '29.jpg'),
            ('Tenis Spiderman', 1000, 70, 'Tenis de piel sintética de Spiderman', 1, '30.jpg'),
            ('Chamarra Assassin´s Creed', 700, 70, 'Chamarra tela con tema de Assassin´s Creed', 1, '31.jpg'),
            ('Gorra Watch Dogs', 200, 15, 'Gorra negra de tela con logo de Watch Dogs', 1, '32.jpg'),
			('Lámpara Green Lantern', 700, 34, 'Lámpara de escritorio con tema de Green Lantern', 3, '33.jpg'),
			('Cama SNES', 2000, 200, 'Cama con cabezera y muebles de Super Nintendo', 3, '34.jpg'),
            ('Espejo Star Wars', 400, 50, 'Espejo de pared del Halcón Milenario', 3, '35.jpg'),
            ('Lámpara Mario Bros', 500, 30, 'Lámpara de noche de cubo de Mario Bros', 3, '36.jpg'),
            ('Lámpara Estrella de la Muerte', 600, 40, 'Lámpara de pared de la estrella de la muerte de Star Wars', 3, '37.jpg'),
            ('Réplica Keyblade', 1700, 100, 'Réplica de espada Keyblade de Kingdom Hearts', 4, '38.jpg'),
            ('Medallas Pokémon', 500, 70, 'Medallas de Gimnasio Pokémon', 4, '39.jpg'),
            ('Yugioh Duel Disk', 400, 25, 'Disco de duelo de estantería de Yugioh', 4, '40.jpg'),
            ('Réplica escudo', 2000, 200, 'Réplica de escudo de Capitán América', 4, '41.png'),
            ('Libro Harry Potter', 300, 16, 'Libro de Harry Potter y el niño maldito', 6, '42.jpg'),
            ('Libro Assassin´s Creed', 250, 15, 'Libro de Ezio en Assassin´s Creed', 6, '43.jpg'),
            ('Libro Animales Fantásticos', 350, 17, 'Libro Animales fantásticos y dónde encontrarlos', 6, '44.jpg'),
            ('Libro Video Game', 300, 16, 'Libro de a brief story history of video games', 6, '45.jpg'),
            ('Libro Mass Effect', 400, 19, 'Libro de Mass Effect Universe', 6, '46.jpg'),
			('Comic Infinity War', 300, 16, 'Comic Marvel y el Guantelete del infinito', 6, '47.jpg'),
			('Comic Injustice', 200, 14, 'Comic DC Injustice', 6, '48.jpg'),
			('Comic Civil War', 300, 16, 'Comic Marvel Civil War', 6, '49.jpg'),
			('Comic Star Wars', 400, 18, 'Comic de Star Wars a new hope', 6, '50.jpg'),
			('Comic Kick Ass', 200, 14, 'Comic Marvel y el Guantelete del infinito', 6, '51.jpg');