use nerdstuff;

insert into producto(nombreProducto, costo, puntaje, descripcion, idCategoria, direccionFoto)
	values 	('Llavero Thor', 100, 7, 'Llavero de Mjolnir de Thor.', 2, '01.jpg'),
			('Playera Capitan America', 100, 7, 'Playera algodón Capitan America.', 1, '02.jpg'),
            ('Casco Iron Man', 2000, 120, 'Casco de plástico de Iron Man con luz interior.', 2, '03.jpg'),
            ('Cartera Deadpool', 300, 17, 'Cartera de piel con logo de Deadpool', 2, '04.jpg'),
            ('Figma Link', 1300, 80, 'Figura de plástico de Link.', 5, '05.jpg'),
            ('Taza Game of Thrones', 400, 22, 'Taza de cerámica de Game of Thrones.', 2, '06.jpg'),
            ('Funko Pop Goku', 350, 22, 'Figura de vinil de Goku.', 5, '07.jpg'),
            ('Funko Pop Mario', 350, 22, 'Figura de vinil de Mario.', 5, '08.jpg'),
            ('Funko Pop Daredevil', 350, 22, 'Figura de vinil de Daredevil.', 5, '09.jpg'),
            ('Gorra Nintendo', 500, 30, 'Gorra de tela con logo de Nintendo.', 1, '10.jpg'),
            ('Chamarra Overwatch', 1000, 70, 'Chamarra de piel con logo de Overwatch.', 1, '11.jpg'),
            ('Vaso Dragonball', 280, 16, 'Vaso de plástico de Dragon Ball', 2, '12.jpg'),
            ('Protector Celular Mario Bros', 175, 10, 'Protector de goma para celular de Mario Bros.', 2, '13.jpg'),
            ('Réplica Master Sword', 1900, 110, 'Réplica de metal a tamaño real de la Master Sword.', 4, '14.jpg'),
            ('Hebilla Fallout', 200, 14, 'Hebilla de metal de Fallout.', 2, '15.jpg'),
            ('Anillo Green Lantern', 300, 20, 'Anillo de metal de Linterna Verde.', 2, '16.jpg'),
            ('Esferas Dragon Ball', 600, 40, 'Esferas de plástico de Dragon Ball.', 4, '17.jpg'),
            ('Aretes Potara Dragonball', 200, 14, 'Aretes de metal con esferas de plástico de Dragon Ball.', 2, '18.jpg'),
            ('Manga Zelda 1', 180, 10, 'Manga de Legend of Zelda número 1 de 60 páginas.', 7, '19.jpg'),
            ('Manga Zelda 2', 180, 10, 'Manga de Legend of Zelda número 1 de 60 páginas.', 7, '20.jpg'),
            ('Manga Zelda 3', 180, 10, 'Manga de Legend of Zelda número 1 de 60 páginas.', 7, '21.jpg'),
            ('Hyrule Historia', 650, 40, 'Libro con la historia de Hyrule de Legend of Zelda.', 6, '22.jpg'),
            ('Peluche Pikachu', 200, 14, 'Figura de peluche de Pikachu.', 5, '23.jpg'),
            ('Llavero Zelda Boss Key', 175, 10, 'Llavero de metal de Boss Key de Legend of Zelda.', 2, '24.jpg'),
            ('Llavero Star Wars Vader', 175, 10, 'Llavero de metal de casco de Darth Vader de Star Wars.', 2, '25.jpg'),
            ('Cubo Rubik', 130, 10, 'Cubo Rubik de plástico.', 5, '26.jpg'),
            ('Llavero Chip', 40, 3, 'Llavero de circuito impreso.', 2, '27.jpg'),
            ('Mesa Control Nintendo', 1600, 100, 'Mesa con forma de Control de Nintendo.', 3, '28.jpg'),
            ('Banda Naruto', 120, 8, 'Banda de algodón con placa de metal de Naruto.', 2, '29.jpg'),
            ('Tenis Spiderman', 1000, 70, 'Tenis de piel sintética de Spiderman', 1, '30.jpg');